/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PlayRouteImport } from './routes/play'
import { Route as HowRouteImport } from './routes/how'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomNewRouteImport } from './routes/room/new'
import { Route as RoomCodeIndexRouteImport } from './routes/room/$code/index'
import { Route as RoomCodeHostRouteImport } from './routes/room/$code/host'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomNewRoute = RoomNewRouteImport.update({
  id: '/room/new',
  path: '/room/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeIndexRoute = RoomCodeIndexRouteImport.update({
  id: '/room/$code/',
  path: '/room/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeHostRoute = RoomCodeHostRouteImport.update({
  id: '/room/$code/host',
  path: '/room/$code/host',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/play': typeof PlayRoute
  '/setup': typeof SetupRoute
  '/room/new': typeof RoomNewRoute
  '/room/$code/host': typeof RoomCodeHostRoute
  '/room/$code/': typeof RoomCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/play': typeof PlayRoute
  '/setup': typeof SetupRoute
  '/room/new': typeof RoomNewRoute
  '/room/$code/host': typeof RoomCodeHostRoute
  '/room/$code': typeof RoomCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/play': typeof PlayRoute
  '/setup': typeof SetupRoute
  '/room/new': typeof RoomNewRoute
  '/room/$code/host': typeof RoomCodeHostRoute
  '/room/$code/': typeof RoomCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how'
    | '/play'
    | '/setup'
    | '/room/new'
    | '/room/$code/host'
    | '/room/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how'
    | '/play'
    | '/setup'
    | '/room/new'
    | '/room/$code/host'
    | '/room/$code'
  id:
    | '__root__'
    | '/'
    | '/how'
    | '/play'
    | '/setup'
    | '/room/new'
    | '/room/$code/host'
    | '/room/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowRoute: typeof HowRoute
  PlayRoute: typeof PlayRoute
  SetupRoute: typeof SetupRoute
  RoomNewRoute: typeof RoomNewRoute
  RoomCodeHostRoute: typeof RoomCodeHostRoute
  RoomCodeIndexRoute: typeof RoomCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/new': {
      id: '/room/new'
      path: '/room/new'
      fullPath: '/room/new'
      preLoaderRoute: typeof RoomNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code/': {
      id: '/room/$code/'
      path: '/room/$code'
      fullPath: '/room/$code/'
      preLoaderRoute: typeof RoomCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code/host': {
      id: '/room/$code/host'
      path: '/room/$code/host'
      fullPath: '/room/$code/host'
      preLoaderRoute: typeof RoomCodeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowRoute: HowRoute,
  PlayRoute: PlayRoute,
  SetupRoute: SetupRoute,
  RoomNewRoute: RoomNewRoute,
  RoomCodeHostRoute: RoomCodeHostRoute,
  RoomCodeIndexRoute: RoomCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
